Blog app: add authorization rules
SanaTameem/blog-app pull request #10
Opened 2023-10-20 22:12 UTC by SanaTameem

# [Project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_add_authorization.md#project-requirements)

- Install CanCanCan in your project.
- Add a role column to the users table. Remember to use a migration for this.
- A user can delete a post if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
  - For that you need to implement the post deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.
- A user can delete a comment if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
  - For that you need to implement the comment deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.

2023-10-20 23:10 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi team, 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- The authorization rules have successfully been set up. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-20 23:10 UTC, ridwanediallo commented on app/views/posts/show.html.erb
> +                    <% end %>
- [ ] Well done implementing the authorization feature 👏. However, please let's ensure that the `Delete` button is only visible if the signed-in user is an `admin` or the `owner` of the post. :ok_hand: 
At this moment, the `Delete` button is visible to unauthorized users, which violates one of the project requirements. Kindly, let's fix that.

### Requirement :point_down: 
![Screenshot from 2023-10-20 23-03-14](https://github.com/SanaTameem/blog-app/assets/89228743/a76cacbd-ca43-4aff-ad62-5bcdd353b11e)

2023-10-20 23:10 UTC, ridwanediallo commented on app/views/posts/show.html.erb
> +                            <%= button_to 'Delete Comment', user_post_comment_path(user_id: comment.user_id, post_id: comment.post_id, id: comment.id), method: :delete, data: { confirm: 'Are you sure
- [ ] Well done implementing the authorization feature 👏. However, please let's ensure that the `Delete` button is only visible if the signed-in user is an `admin` or the `owner` of the comment. :ok_hand: 
At this moment, the `Delete` button is visible to unauthorized users, which violates one of the project requirements. Kindly, let's fix that.


### Requirement :point_down: 
![Screenshot from 2023-10-20 22-43-05](https://github.com/SanaTameem/blog-app/assets/89228743/d815e923-beb3-4adc-aca9-209a431e814d)

2023-10-21 04:13 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Sana,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Good job on implementing recommended changes!
🎲 ReadMe looks great!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
Let's make the ReadMe stand out even better by including instructions under the _Getting Started_ section, on how to run the app, for instance, using the command `rails s`.

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-21 04:16 UTC, SanaTameem commented
@ridwanediallo 
@rloterh 
Thank you for reviewing our project and for taking the time to provide your valuable feedback. I sincerely appreciate it.

2023-10-21 04:17 UTC, merged